macro(configure_glog)
    message(STATUS "Configureing glog...")
    option(BUILD_TESTING "" OFF)
    option(WITH_GFLAGS "" OFF)
    add_subdirectory(${DNN_ROOT_DIR}/third_party/glog third_party/glog/)
endmacro()
