macro(configure_protobuf)
    message(STATUS "Configuring protobuf...")
    option(protobuf_BUILD_TESTS "" OFF)
    option(protobuf_BUILD_EXAMPLES "" OFF)
    option(protobuf_BUILD_SHARED_LIBS "" ON)
    option(protobuf_BUILD_PROTOC_BINARIES "" ON)
    add_subdirectory(${DNN_ROOT_DIR}/third_party/protobuf/cmake third_party/protobuf/)
endmacro()
